---
- name: Practice Delegate To tasks
  hosts: nodes
  tasks:
    - name: Execute uptime command
      command: uptime
      register: out
    - debug:
        msg: "{{ out.stdout }}"
    
    - name: Create a new file on the local host with the Uptime of the Server 
      file:
        path: ./new_file_from_delegate_task 
        state: touch
      delegate_to: localhost
      run_once: true

    - name: Update the contents in the file
      lineinfile:
        path: ./new_file_from_delegate_task
        line: "{{ out.stdout }}"
        state: present
      delegate_to: localhost  
        
