---
- name: Demo Debug
  hosts: localhost
  gather_facts: true
  tasks:
    - name: execute whoami command
      command: whoami
      register: out
    - debug:
        msg: "this is the output of the command {{ out }} !"
