---
- name: Demo Debug
  hosts: nodes
  gather_facts: true
  tasks:
    - name: execute whoami command
      command: whoami
      register: out
    - debug:
        msg: "this is the output of the command {{ out }} !"

    - name: Print the Hostname, Server IP, NTP and DNS
      debug:
        msg: 
          - "Hostname of the Server is : {{ inventory_hostname }} !"
          - "Ip address of the Server is : {{ server_ip }} !"
          - "NTP Server is : {{ ntp_server }} !"
          - "DNS of the Server is : {{ dns_server }}"


